Update to JS 1.15.13 to fix Chrome 124 compatibility breakage
livekit/client-sdk-unity-web pull request #49
Opened 2024-03-26 21:10 UTC by davidzhao

2024-03-27 02:12 UTC, cloudwebrtc approved these changes

2024-03-27 09:54 UTC, theomonnom requested changes
You need to run `buildunity` and `build` of Bridge~

2024-03-27 20:06 UTC, davidzhao commented
> You need to run `buildunity` and `build` of Bridge~

done!

2024-03-28 18:38 UTC, theomonnom approved these changes

2024-03-28 18:39 UTC, merged